name: Update Weather Forecast SVG

on:
  push:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  update-weather-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Debug Information
        run: |
          echo "触发事件: ${{ github.event_name }}"
          echo "当前分支: ${{ github.ref }}"
          echo "提交SHA: ${{ github.sha }}"

      - name: Checkout WeatherPainting
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Start Express Server
        run: npm run start & sleep 5

      - name: Generate SVG
        run: npm run paint

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./src/weather_forecast.svg
          git commit -m "Update weather forecast SVG" || exit 0
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
